apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.app }}
    spec:
      containers:
      - name: {{ .Values.backend.deployment.containers.name }}
        image: {{ .Values.backend.deployment.containers.image }}
        ports:
        - containerPort: {{ .Values.backend.deployment.containers.containerPort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.deployment.containers.name }}
        image: {{ .Values.frontend.deployment.containers.image }}
        ports:
        - containerPort: {{ .Values.frontend.deployment.containers.containerPort }}
        args: ["-port={{ .Values.frontend.service.targetPort }}", "-P:ktor.backend.port={{ .Values.backend.service.port }}", "-P:ktor.backend.host={{ .Values.backend.name }}"]