apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.app }}
  ports:
  - protocol: {{ .Values.backend.service.protocol }}
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.app }}
  ports:
  - protocol: {{ .Values.frontend.service.protocol }}
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}