stages:
  - build

Building:
  stage: build
  tags:
    - docker
  services:
  - docker:19.03.12-dind
  image: docker
  script:
    - docker build \
     -t autobol/course_project:frontend --build-arg YARN_VERSION=$YARN_VERSION GRADLE_VERSION=$GRADLE_VERSION NODE_VERSION=$NODE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/course_project:frontend
