stages:
  - pre-build
  - build
  - deploy

.job_template: &job_config
  tags:
    - docker
  services:
    - docker:19.03.12-dind
  image: docker

Pre-building:
  stage: pre-build
  <<: *job_config
  script:
    - docker build `
     `-t $DOCKER_USER/image_for_build_front:latest `
     `-f ./Dockerfile.pre-build `
     `--build-arg ALPINE_VERSION=$ALPINE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/image_for_build_front:latest
  rules:
    - if: '$RUN_REBUILD_IMAGE_FOR_BUILD != "no"'
      when: always
    - when: never


# Building:
  stage: build
  <<: *job_config
  script:
    - docker build `
     `-t $DOCKER_USER/frontend:latest `
     `--build-arg YARN_VERSION=$YARN_VERSION `
     `--build-arg GRADLE_VERSION=$GRADLE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/frontend:latest

Deploy:
  stage: deploy
  tags:
    - aws_deploy
  script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl
