stages:
  - pre-build
  - build
  - deploy

.job_template: &job_config
  tags:
    - docker
  services:
    - docker:19.03.12-dind
  image: docker

Pre-build:
  stage: pre-build
  <<: *job_config
  script:
    - docker build `
     `-t $DOCKER_USER/image_for_build_front:latest `
     `-f ./Dockerfile.pre-build `
     `--build-arg ALPINE_VERSION=$ALPINE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_USER/image_for_build_front:latest
  rules:
    - if: '$RUN_REBUILD_IMAGE_FOR_BUILD != "no"'
      when: always
    - when: never


Build:
  stage: build
  <<: *job_config
  script:
    - docker build `
     `-t $DOCKER_REGISTRY/frontend:latest `
     `--build-arg YARN_VERSION=$YARN_VERSION `
     `--build-arg GRADLE_VERSION=$GRADLE_VERSION .
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - docker push $DOCKER_REGISTRY/frontend:latest

Deploy_dev:
  stage: deploy
  needs:
    - Build
  tags:
    - aws_dev_deploy
  script:
    - sed -i "s/NAMESPACE/$NAMESPACE_DEV/g" ./app-deploy-chart/values.yaml
    - sed -i "s/TAG/latest/g" ./app-deploy-chart/values.yaml
    - helm upgrade app app-deploy-chart


Deploy_prod:
  stage: deploy
  tags:
    - aws_prod_deploy
  script:
    - sed -i "s/NAMESPACE/$NAMESPACE_PROD/g" ./app-deploy-chart/values.yaml
    - sed -i "s/TAG/prod/g" ./app-deploy-chart/values.yaml
    - helm upgrade app app-deploy-chart
