stages:
  - pre-build
  - build
  - deploy
  - rollback

include:
  - local: '/jobs/builds.yml'   # pre-build; build
  - local: '/jobs/deploy.yml'   # deploy
  - local: '/jobs/rollback.yml' # rollback
