backend:
  app: backend
  name: backend-deployment

  replicaCount: 1

  deployment:
    containers:
      name: backend-cnt
      image: autobol/backend:TAG
      containerPort: 80
  
  service:
    protocol: TCP
    port: 80
    targetPort: 8080


frontend:
  app: frontend
  name: frontend-deployment

  replicaCount: 1
  
  deployment:
    containers:
      name: frontend-cnt
      image: autobol/frontend:latest
      containerPort: 80

  service:
    protocol: TCP
    port: 80
    targetPort: 8080



ingress:
  name: application-deployment
  app: application-deployment
  host: dev-school-app.NAMESPACE.school.telekom.sh
  path: /
  pathType: Prefix
