apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.containers.name }}
        image: {{ .Values.deployment.containers.image }}
        ports:
        - containerPort: {{ .Values.deployment.containers.containerPort }}
        args: 
          - -port={{ .Values.service.targetPort }}
          - -P:ktor.backend.port={{ .Values.backend.port }}
          - -P:ktor.backend.host={{ .Values.backend.name }}
