apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: {{ .Values.issuer.secretKey }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.class }}
