app: frontend
name: frontend-deployment

replicaCount: 1
  
deployment:
  containers:
    name: frontend-cnt
    image: autobol/frontend:TAG
    containerPort: 80

service:
  protocol: TCP
  port: 80
  targetPort: 8080

ingress:
  class: nginx
  secretName: tls-secret
  host: dev-school-app.NAMESPACE.school.telekom.sh
  path: /
  pathType: Prefix

issuer:
  email: vladimir.autobol@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  secretKey: acme-account-key

backend:
  port: 80
  name: backend-deployment
